### ISSUE TITLE
unexpected argument to `test`

### ISSUE THREAD

**Issue by mwilliammyers** [vkovtash/pure#1]
Awesome port!

I just encountered an error when `cd`ing into a git repo. I haven't looked into why it happens yet though but just FYI

```
test: Unexpected argument type at index 0
test: Missing argument at index 2
test: Missing argument at index 2
```

**Comment by vkovtash** [comment]
Thanks!
I know that bug. Just haven't enough time to fix it right now.

**Comment by mwilliammyers** [comment]
No problem, no rush! Just making sure you knew.
