### ISSUE TITLE
config.fish being reloaded at random times

### ISSUE THREAD

**Issue by mohd-akram** [vkovtash/pure#3]
To test, add this to config.fish:

`echo "reloading"`

and open a new shell and `cd` to a git repo, press Enter many times, the shell will output `reloading` seemingly randomly.

This is causing an issue for me with another plugin (adambrenecki/virtualfish#98).

Tested on OS X El Capitan.

**Comment by vkovtash** [comment]
If you add to config.fish:

```
echo "reloading" %self
```

you will see that config of current shell is not reloaded. First "reloading" message created by current shell. And next messages created by child fish processes.

I use child fish processes to perform asynchronous git status updates. Unfortunately there is no better ways to perform asynchronous tasks in fish.
The only solution I can propose is to make asynchronous updates optional. In synchronous mode there will be no child fish processes but prompt will render much slower.

**Comment by vkovtash** [comment]
Also you may just suppress stderr output like this

```
eval (python -m virtualfish auto_activation compat_aliases projects ^ /dev/null)
```

or stderr and stdout output like this 

```
eval (python -m virtualfish auto_activation compat_aliases projects > /dev/null ^&1)
```

**Comment by mohd-akram** [comment]
Is it possible to set a variable/flag in the child process that's running? This way I can wrap my config.fish file in an if condition and only run it if that variable is not set.

**Comment by vkovtash** [comment]
It is possible, but I am not sure it'll help.

I believe fish executes config.fish at the very beginning of lifecycle. It
may be executed before flag is set.

Anyway, lets try. I'll give you updated version shortly.

**Comment by vkovtash** [comment]
Checkout that branch https://github.com/vkovtash/pure/tree/feature/PURE-3.
PURE_ASYNC_TASK variable is set for all child fish instances created by pure prompt.

**Comment by mohd-akram** [comment]
That works great, thanks!
